#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by localhost - 2024/10/09 11:39:23
# Search URL: http://localhost:8080/esg-search/wget?dataset_id=CMIP6.ScenarioMIP.EC-Earth-Consortium.EC-Earth3-Veg.ssp370.r1i1p1f1.AERmon.od550aer.gr.v20220511|esgf-data1.llnl.gov
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://localhost:8080/esg-search/wget?dataset_id=CMIP6.ScenarioMIP.EC-Earth-Consortium.EC-Earth3-Veg.ssp370.r1i1p1f1.AERmon.od550aer.gr.v20220511|esgf-data1.llnl.gov'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_201501-201512.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_201501-201512.nc' 'SHA256' '3f810b8e7722b91e084b887ea1f9d975a2b453d3ec25cb46b29a9cffa17eaf91'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_201601-201612.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_201601-201612.nc' 'SHA256' '002188311189ab4e896c9f189315c28f0eaac145e4477bd45546388faa61b0e7'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_201701-201712.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_201701-201712.nc' 'SHA256' '852fb7bfe8b6c87ffa16a8251fcb656849777aa99ac6c1f3c1b8cd26a5876d46'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_201801-201812.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_201801-201812.nc' 'SHA256' '562095a464ec98177ef7994081ee3b0b5316bcc84c396227c2b360449d5637f3'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_201901-201912.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_201901-201912.nc' 'SHA256' 'fb1219028077217f219f5c7a4acdd2d65749e2e2e1c04696a3a889dc906b248f'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202001-202012.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202001-202012.nc' 'SHA256' '063541b0e6fc1a192748239168b223825d8bbab680d6cc9b206b198f61c40429'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202101-202112.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202101-202112.nc' 'SHA256' '74434774e157ed0828849c5b8e18e3f050d630b36f52cffc2df88d77d5aeffce'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202201-202212.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202201-202212.nc' 'SHA256' 'e237bcadcd727f00116b3b3da4001c351ee5e613c909e52f05510bfdfa3bf2db'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202301-202312.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202301-202312.nc' 'SHA256' '59924cd999ca1dec35bf0885752c31b361f6bd931fc0716f7c0451d1f03fdafd'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202401-202412.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202401-202412.nc' 'SHA256' '2c34ef66ec16a8949d8a404fa14013eb757944d37b8607bd9c8b56a5c885bbf6'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202501-202512.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202501-202512.nc' 'SHA256' 'aef8c056a75eb8c29081e9f0b8c5df263f1a9c07fb1a7639a7fc7d015aec3205'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202601-202612.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202601-202612.nc' 'SHA256' 'b4fcaf7b98abf70006c00b7602d7a60a165279e392c0b7c1077fa18a818f4dbe'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202701-202712.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202701-202712.nc' 'SHA256' '8c11bceb2d6087e886dfe2715fe7e3a91efac698f53617e20ab9e691cb2b6360'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202801-202812.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202801-202812.nc' 'SHA256' '14f246f8a78589c27030e889b9c4065c5f806ee308bcfe8676320ea5c3d3a702'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202901-202912.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_202901-202912.nc' 'SHA256' '51ab7412b7ed7636d0b0801fe2b8bd847380c1a3c4c4476e0c584bebe54fa807'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203001-203012.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203001-203012.nc' 'SHA256' 'bc8cfd90da8a8bdc7215b3a67252dba617f11a72f998adb7b95b17429531d9bb'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203101-203112.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203101-203112.nc' 'SHA256' '7fe0adf6c54726ddb4ff4d7baf9c8664aa741e61fadcaa32cb6d18aed6ebc57d'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203201-203212.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203201-203212.nc' 'SHA256' '0136d358ae2a5ab974c044f4b1f096da8d05b5b2333f2081b050b80b1ef39251'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203301-203312.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203301-203312.nc' 'SHA256' '6f64676e78527cf60140a22a9cb785f32e39ab65c014db2c1d085d4515f7e5b4'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203401-203412.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203401-203412.nc' 'SHA256' '8d7d8e369b2f560be7e0933f4aeaf4161e5dbcd3d4e32fed52cf3dd5a9e2fc78'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203501-203512.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203501-203512.nc' 'SHA256' 'e03f9e639f1f127c5076611b001cc16006a73ac6e453c8cf42196331af818cc1'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203601-203612.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203601-203612.nc' 'SHA256' '6d12f4b70c962dc2d42e6cf01a53034749b5c3e8dcf109d32702fedfdbf9388d'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203701-203712.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203701-203712.nc' 'SHA256' 'dc87230f5a5d8eaee6178e668181c2e24c4ed50eee5ed5290ea2e67a3b309dcc'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203801-203812.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203801-203812.nc' 'SHA256' 'f8fc084a17aff0e4af6ec55cb38c1252befdef6b695f16774bf91066618aedb5'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203901-203912.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_203901-203912.nc' 'SHA256' '0a7d126ee9115fb6c8fb7978366159b5c2f90c45c20b101aa651924e46f88be4'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204001-204012.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204001-204012.nc' 'SHA256' '3740d3f55dd9a78c1323eb993107c2bbb3b455716504fcddb41ee6796ac2ad5b'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204101-204112.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204101-204112.nc' 'SHA256' '649109388cdebc702833b2d738297d2314a53c6330cc3e4236b5a883cfb82667'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204201-204212.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204201-204212.nc' 'SHA256' 'eb18982a7d1d384add94b22a92d948c937f74b93a8d591f8c2eefc1b9462e9f8'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204301-204312.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204301-204312.nc' 'SHA256' '0827744a686d4fd34b0115a6092c9ebc8a5ce6637823c5dc8b1d972c6ff98105'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204401-204412.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204401-204412.nc' 'SHA256' 'ef46051a121af7397241bd35dbb2f30014f8dbaa8773b779d56dbfecb111c497'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204501-204512.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204501-204512.nc' 'SHA256' 'd193f94857a7bc38de8dca84030a4bc41283091149c7e3a05ef8ad3b61bfc53b'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204601-204612.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204601-204612.nc' 'SHA256' '49474528df62f561f0e0ac777ca6329979dcc33be809e7d0d4257084b7702c9d'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204701-204712.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204701-204712.nc' 'SHA256' 'ddcc416f0d1fdbc731c08706765dcfdcaadfaa2e87cd704b172699c8cb2b35ed'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204801-204812.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204801-204812.nc' 'SHA256' '70d5b331b09b908f22cd3d69fc8978236bf1f559b751d5a6983976f205f2bc26'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204901-204912.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_204901-204912.nc' 'SHA256' '85f2c75bd27eabd9e45385fa1fa9d24c305aa059f2939ef6dd9457a11419a87e'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205001-205012.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205001-205012.nc' 'SHA256' '0b03ed75dd726b9779c3c15a581c7c18f47a08b276db9f67213d725462df0dfd'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205101-205112.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205101-205112.nc' 'SHA256' '8b30590b7a0e19d7b18fb9354f2ed3b4b68f5f21cb0deb9fcb0261f1888a8625'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205201-205212.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205201-205212.nc' 'SHA256' 'ee31df22ef3b3a699f9680eceea05af39153b6cf2205625b93eea9211cdb6b17'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205301-205312.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205301-205312.nc' 'SHA256' 'bd555ecb24e40fafa2247bbe45b0e477ef0b3c04f86bae6e7a8c683c86205166'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205401-205412.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205401-205412.nc' 'SHA256' 'cee74d5050cb64eabfa7938714c16eca4df26e889d5109aaea2b0ff4a3246194'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205501-205512.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205501-205512.nc' 'SHA256' '46b7be86de9a53f7bcd78d7ede58bfc97b4fa218aff54d91719c0e6795d8102f'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205601-205612.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205601-205612.nc' 'SHA256' 'a4593ef5fe967bd299fce5ea24fdc15220e969dd19d46d84672b878ea0b41e1e'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205701-205712.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205701-205712.nc' 'SHA256' '7911c3e82652a58f28c122e70366c5b70d7d484942a19376cb94afca24bafc72'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205801-205812.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205801-205812.nc' 'SHA256' 'f12c4ffb62632b5fbc45abf102cc56ad2bdcf605b36d77e8e605162a2ce51f33'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205901-205912.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_205901-205912.nc' 'SHA256' 'e909c89369a0415938b7bfc0c1ea0f7422e5e37b3c75e4221718f80dfc19f3d3'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206001-206012.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206001-206012.nc' 'SHA256' '75a4c19b30cebb92dc54b0cb87ae4675aaf515997de39165a313e5e46f68cdfc'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206101-206112.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206101-206112.nc' 'SHA256' '159918321b25d28dcbf00111c8f89b273998a79ae1847cfd31ebf76d6e94a60a'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206201-206212.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206201-206212.nc' 'SHA256' '06f37eab2a55a9b29bc4d83ad4b8590c8f32e0cca84f9530b84932e3d6510d58'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206301-206312.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206301-206312.nc' 'SHA256' '05c092dbe9f3f4339d9aa239e33d2d940f2c62a7b8ae9111ef095b0f87a9275f'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206401-206412.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206401-206412.nc' 'SHA256' 'e621fd1aad913302d612274cc3d040f1f2b595e0f418064dca755f5ee9822ff7'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206501-206512.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206501-206512.nc' 'SHA256' '0803fa9de4a57951a765f0e710c4cd2928e679ddb6560f2ea3baafd578a954f1'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206601-206612.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206601-206612.nc' 'SHA256' 'cf3fda3618310b7974979c22b8e3d0cf8806e8ce3f4e1b0390f608bee3ae941d'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206701-206712.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206701-206712.nc' 'SHA256' 'feaa8ebb20c9acea2b8e1cc26394378162d48eedea72eee511a4902c353317af'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206801-206812.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206801-206812.nc' 'SHA256' 'a345e94ac9d2b1cc030be3e64ec75b9575d09802256354b78cef4184582a57dd'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206901-206912.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_206901-206912.nc' 'SHA256' '8b3a84b32c2a991e8da136c700b595391a41efacc07f0f8fd88f705204e64afd'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207001-207012.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207001-207012.nc' 'SHA256' 'e512ebff17ccbe652bc771f6a183d8ba5c3a83b120e78d109a4efb47e37f5c25'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207101-207112.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207101-207112.nc' 'SHA256' '402d044514f2ba611f1f6a8eb95b0032ddb8bad622574483f70c85291c29cbd3'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207201-207212.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207201-207212.nc' 'SHA256' 'ee4d08fdbf9a8e57006e3f7312cd117964e821fb095870c3e4e0de776d4d24a3'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207301-207312.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207301-207312.nc' 'SHA256' '64d4a2bebc62706cf541b86e1379dada01fb3b62d43538ccf33b2fdadd960a00'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207401-207412.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207401-207412.nc' 'SHA256' '9c47472540abd3852f8aab393349eca66644136e2443ba9e9651a922b084e202'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207501-207512.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207501-207512.nc' 'SHA256' 'f7efabea611f95e81347625ad3c818fa8999ea115eb3a6fb3c085862d7589067'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207601-207612.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207601-207612.nc' 'SHA256' 'a381a658bf465de90f2c7bd5410199de575da773a787e1d1a3ada8feffc0ed9d'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207701-207712.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207701-207712.nc' 'SHA256' '063b8aa16dc04d6530a9c07d96b95403fb228fc81162fece5fd716738b2ebc25'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207801-207812.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207801-207812.nc' 'SHA256' 'c04857ab525c4441a9022982c97d5882e3b39794d6db4b43be351aa959f478af'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207901-207912.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_207901-207912.nc' 'SHA256' '0c02d017912b3d1ae062fb5443a5e31314c665ecf13754ba67923a44d291966e'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208001-208012.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208001-208012.nc' 'SHA256' 'f1abd2a4949cb5bec27d0541f8f10e4e62d209a19199f7ccd52f5d1fafd65d43'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208101-208112.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208101-208112.nc' 'SHA256' '9ad2307ff5b33bfb4b2583c45224a24ee4e3d8bef1a97280a57ee05c75e1a624'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208201-208212.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208201-208212.nc' 'SHA256' '7ce7acf71e859a7f8fac63a42b0b3d751ef2d55732f12ebe5eeeaba39af03734'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208301-208312.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208301-208312.nc' 'SHA256' '9b46830bcce9909b403c19b457f2261ea334391819a60186e9ed480ac06d8b2a'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208401-208412.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208401-208412.nc' 'SHA256' 'ad9382c4434c71592376f0cffbf3ece627df6db9ad877aa34b17c92b9c313a36'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208501-208512.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208501-208512.nc' 'SHA256' '93559fb0540761323f03fbe6d06a9474d8e78b9b108be2c74e36e5a78f2f80c7'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208601-208612.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208601-208612.nc' 'SHA256' 'bacc2bad8d057928949318d6f07e65d6cea7f0aaba5507ebcebdd0b433b0d52d'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208701-208712.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208701-208712.nc' 'SHA256' '91f74d4e86861aef6107b6e0d75ae64272db722bde20b80b40cb081955966732'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208801-208812.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208801-208812.nc' 'SHA256' '61537c071db4f4f9c8d00cf2dd07c6bdcaf26a35960c45ba8964ef2e460c79f9'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208901-208912.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_208901-208912.nc' 'SHA256' 'fc513a5b31313063a90bbf9f3aa898f015192034162f874bbd2d9be1b5dd790b'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209001-209012.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209001-209012.nc' 'SHA256' '88862ef16b68384099b68d5d1c379cbbefbceeff891eb939ddfe2c4f2371cae5'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209101-209112.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209101-209112.nc' 'SHA256' '0eda6aad3c2fe4a16e5d7489a3cb18ec1d3fabc641c246b994555d1c08468d2a'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209201-209212.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209201-209212.nc' 'SHA256' '25fee922e43664874a7b5dbd0ce9234322d470542b69ed29e94a04438d644e71'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209301-209312.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209301-209312.nc' 'SHA256' 'bba0a528937c35887c08b2623a826fbf1fc45326741c2594fb5a76c37cf78944'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209401-209412.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209401-209412.nc' 'SHA256' '3d53301e5b5d5859f21d87a2a62bdfed4997410f6e1f536358169ac378767f51'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209501-209512.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209501-209512.nc' 'SHA256' '2e02c9ef15deeb0b5dc3c507e74464fdb73e0b41735614eb933cbe2226ba76cc'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209601-209612.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209601-209612.nc' 'SHA256' '293e7cbacb87116c55afd809cc03522cb16bbf4f98420bb13a21806d359b451e'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209701-209712.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209701-209712.nc' 'SHA256' 'b731e6c7b207409568c2c815ff12c2182ede84367db83250072ed4b622741dc5'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209801-209812.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209801-209812.nc' 'SHA256' '8b48f9cbac0f30d7c4eee4cb20277112133243ca7da210c782d719a488de06a3'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209901-209912.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_209901-209912.nc' 'SHA256' 'add40fecfde969f2f995177fc202ab3785166e2e8f5232bd86658974b509c413'
'od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_210001-210012.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r1i1p1f1/AERmon/od550aer/gr/v20220511/od550aer_AERmon_EC-Earth3-Veg_ssp370_r1i1p1f1_gr_210001-210012.nc' 'SHA256' 'ea83e04cc82faaaec2854ea07fb00d76b04710e56e11e5b16597f8da2c41894d'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 86 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
