#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by localhost - 2024/10/09 11:08:21
# Search URL: http://localhost:8080/esg-search/wget?dataset_id=CMIP6.ScenarioMIP.EC-Earth-Consortium.EC-Earth3-Veg.ssp370.r12i1p1f1.Amon.clt.gr.v20200925|esgf.nci.org.au
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://localhost:8080/esg-search/wget?dataset_id=CMIP6.ScenarioMIP.EC-Earth-Consortium.EC-Earth3-Veg.ssp370.r12i1p1f1.Amon.clt.gr.v20200925|esgf.nci.org.au'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_201501-201512.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_201501-201512.nc' 'SHA256' '238b0657b600148318dd2714ba4bf723416a421ffbc16e645c8a7f0dd9d31696'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_201601-201612.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_201601-201612.nc' 'SHA256' '6093faa4dc7930cd53291afaa6201eeeaa1a679a9ecece95968f41b62b4d30cc'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_201701-201712.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_201701-201712.nc' 'SHA256' '25cb025d9a96ca8a4f4b5159b686df52e0304d96e0d42ba351fa24d8a90e6473'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_201801-201812.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_201801-201812.nc' 'SHA256' '8acd78ef6958a72a62612764375ed2410bd8358ba7153c2392f7b42fa45f4ac7'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_201901-201912.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_201901-201912.nc' 'SHA256' 'c5cc32a96ce7e1d93e83872ad13b255f62fcef23c477062d8fc6fe147b29cce5'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202001-202012.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202001-202012.nc' 'SHA256' '1c734dc6e186af6239350d6d250c6a4ee03ecb5abfd9832864e2f09c871ff4a9'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202101-202112.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202101-202112.nc' 'SHA256' '72a4f5babcdb6ff636edc38992d5005488605e195875e99b0bbaf5de842e30b0'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202201-202212.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202201-202212.nc' 'SHA256' 'b4c9b1dadac037f4f55bc52de77dc28aa1e7a602e4cd4718d625724932ccabd3'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202301-202312.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202301-202312.nc' 'SHA256' '3a44e1ba7819957c5ea7ec887aee9a3694ac3c658e06eb461212d1ca0f20b5eb'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202401-202412.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202401-202412.nc' 'SHA256' '7c964af28d6c4a79b7f39849114c797f28b1fd5d1d28a66429a085c5b3eceacc'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202501-202512.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202501-202512.nc' 'SHA256' 'edfb0d9577f043a3d538f1ca363b6ce578efbc9317b396f6de42ec2f87aa6fae'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202601-202612.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202601-202612.nc' 'SHA256' 'c8c86c179e8a3fb8587e3dc603fd79ea9cc6203063469e982d12c5432d108938'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202701-202712.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202701-202712.nc' 'SHA256' 'f8d8a7d806794a21642eeafa3e48b940293aebd53c73714ed3f1f32504dc5259'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202801-202812.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202801-202812.nc' 'SHA256' '589399bdc78b19c6c6d415fb3de93adaca69eb4f533b2eceb4c9475872e22977'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202901-202912.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_202901-202912.nc' 'SHA256' '69ed7a0cf02cfa37489529256472127520b202743330e8940151451b27ca0a4e'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203001-203012.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203001-203012.nc' 'SHA256' '6eea02a4dd0cdd5ea1afa1ed9fc8b19b8da2efc15881bfe8949cb5692ef1af75'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203101-203112.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203101-203112.nc' 'SHA256' '1f10469a2b8920822e1d84aa87ea45acc97d7ddc2dd5a062a21ffba2ecd29efc'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203201-203212.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203201-203212.nc' 'SHA256' '18cd6f0470edd7a3f715e35f929e8395441131844eb84bd041495aa169a23823'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203301-203312.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203301-203312.nc' 'SHA256' '9b770743d89de8e44c97a9d26d598bad911e1e271c0aca069e6936e978354e65'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203401-203412.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203401-203412.nc' 'SHA256' '25305e3cfa6b810cde879bbb0c01bfa99b9584e79706cf739b5cfa2c9fc25687'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203501-203512.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203501-203512.nc' 'SHA256' '07fbb9129698c50d20b311957b22f47e0a11810758a90520a2174e5e5c8b6835'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203601-203612.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203601-203612.nc' 'SHA256' '9f3637295e9ec68f16a1e899883fe8a98a193964b904389151d65525072f32c0'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203701-203712.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203701-203712.nc' 'SHA256' '55375f1a2b42e1b1f93959fd86e40e5e18ebe42c8d727077aa53cf143520a296'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203801-203812.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203801-203812.nc' 'SHA256' '640f69c908341d5a252ac90f08579ed80cc05345507ebdf763e60d4b8e5f68fa'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203901-203912.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_203901-203912.nc' 'SHA256' 'fcdc07bc4ba7df0a31376c2a9de0500032545bef72be21d6884b97afea3c97d6'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204001-204012.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204001-204012.nc' 'SHA256' '9266c13ed8b8b997ea506013493d88c77fc8ee33930fdf69fdce1d9a4933540a'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204101-204112.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204101-204112.nc' 'SHA256' 'ae61d94e134f5044c47616fc3502e2f8c6574bb861f6ef4050d2a723ebf48641'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204201-204212.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204201-204212.nc' 'SHA256' '4552f5c3cddcd9d479a8a1e6c0ba41d2786a93905a611b5f441afb3eab156339'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204301-204312.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204301-204312.nc' 'SHA256' '50723db0eba67812114ea11f8a899bf269993a2000905ad3f5412d84a7c68ea3'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204401-204412.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204401-204412.nc' 'SHA256' 'b6911e9fb5474dbce58947596c75df7a9d9daed5407c66aca99dedb83bbd8588'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204501-204512.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204501-204512.nc' 'SHA256' '6bd9ec596016b748b7409e63373e1d97722f4683e88a021f5b41126f92542d88'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204601-204612.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204601-204612.nc' 'SHA256' 'a43dd3be27901eb14ba934c2cd719b0619a4db4d3d5f9f12f4fa926cec461b9e'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204701-204712.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204701-204712.nc' 'SHA256' 'f4f09ec0a81e28b266455543e839a6393d7475cc43ff821b7fa09452e63511ab'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204801-204812.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204801-204812.nc' 'SHA256' 'ebed67d74e011911b767d30ca1945fcb4e37c71993b8e5026189fe4c6272aca7'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204901-204912.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_204901-204912.nc' 'SHA256' '816b52acdcb203dc8e64a1a201986d2396d3c503b58984ac445c3967754fc5c4'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205001-205012.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205001-205012.nc' 'SHA256' '5d56f34152a435c4950cf6dbd1cec881b3dcefd6cc30a3b3809b3992ab39ba8a'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205101-205112.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205101-205112.nc' 'SHA256' '60629b7b7e41859512002e56b1d4cd95d0c9bde88f58d4566b487223b4249f13'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205201-205212.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205201-205212.nc' 'SHA256' '11c39fa45914ec7a5af5946691dd6d27a648601dc5bbd3ab6c4c0ce8ce860f33'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205301-205312.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205301-205312.nc' 'SHA256' '6b3ab3133729b1a726d719b4e450a27d435f83effb16e9f6bab8be36b5a30fd0'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205401-205412.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205401-205412.nc' 'SHA256' 'd94f8ab9ff79939f3a9275ef15d248ffde8e42de7cd547c1450f7aba6bd83238'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205501-205512.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205501-205512.nc' 'SHA256' '5633d7f961fb6b111de999d4b61da9ba502f8baa9f925cb62ac01a6dd7b4252a'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205601-205612.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205601-205612.nc' 'SHA256' 'f504db9c46c35a26fa99bde2141ebf086461f7767b917c30d52236d6f42ba4ca'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205701-205712.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205701-205712.nc' 'SHA256' '32b481780d3b4d6f3379f5682ff7d35a27dee3ae46799a1183388dda4ae76895'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205801-205812.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205801-205812.nc' 'SHA256' '39699947de44ff318e3a240e6b373b86cc5e47128a7a4cc5e3dac4bb8502c45d'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205901-205912.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_205901-205912.nc' 'SHA256' '91a65aa4eaf1efbd69ede7a5b2c713c241c9f01ec228b4712378fba4ff0694f4'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206001-206012.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206001-206012.nc' 'SHA256' 'ed25856b4a23e3b837abf438261776710a36b57cae454067de1172eacf016674'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206101-206112.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206101-206112.nc' 'SHA256' '6c87c1590a3726e03c27475a88fe80a45dc811f60bfd4e37b3c97ba942d72c0a'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206201-206212.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206201-206212.nc' 'SHA256' '14493bfe37630e5f397709743bfd51fafe01f6127867922523dd406ad85819a2'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206301-206312.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206301-206312.nc' 'SHA256' '9f5bb4ac3551cebf529db8a39b1f29d829a31f744e5c4f526056ef71280ad3ee'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206401-206412.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206401-206412.nc' 'SHA256' '70ecfe2f4dae810396acfe077ce208570921087fa0f98e314e6cb8c8e8db8d71'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206501-206512.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206501-206512.nc' 'SHA256' 'c418edce647fc77816e5a050e90db2a76a2f074ede8d17a79a5fe8552aba87c5'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206601-206612.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206601-206612.nc' 'SHA256' '718f17a39ca0d0fea4acb85c66c0e76afb7492946b249123477aa1d65d46e0fb'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206701-206712.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206701-206712.nc' 'SHA256' '3879b2d5aab5fec275553c61ad3deba3a353bbef315ccb5640b3ea94bc3c0a64'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206801-206812.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206801-206812.nc' 'SHA256' '247457b9af6376a110f32112695c707dff31496d8b3ed8e88d410a148b3811d2'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206901-206912.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_206901-206912.nc' 'SHA256' '427f63c02ad4f5860406c37e26c616dd935f3a3f76515970a15f2a4d6e9c8592'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207001-207012.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207001-207012.nc' 'SHA256' '293af5b42b4ea5ae4c37dc375e0f965833c60f349139fa384cb59b057eee3285'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207101-207112.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207101-207112.nc' 'SHA256' '6dbbef1e7279be51cbcd6322845328bc8552e0ca3d40c8dffe43ed4b26d82f0a'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207201-207212.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207201-207212.nc' 'SHA256' '2711745e0a47f310a7214e5f7e452ac988bfb04f3ab8431194fee628018ecc6a'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207301-207312.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207301-207312.nc' 'SHA256' '95bcd4e6b229e8ed7d0e03b97559819c6b2a423b7385a499976e774187d54f74'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207401-207412.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207401-207412.nc' 'SHA256' 'a4cf48c8898a5f9ce9f5cbae07e91df9704546522f6a016d09a06676c8c7a03c'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207501-207512.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207501-207512.nc' 'SHA256' '27061ade8110f9b99ae50a3b8bf64fc054c7ba79239a5c5e56b985581698999c'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207601-207612.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207601-207612.nc' 'SHA256' '207581f49af99514f3b10814f086043f64a36c267874d188fd44313a9b6db428'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207701-207712.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207701-207712.nc' 'SHA256' 'b7a55bcdf07a33665c6faddbfa039bce0eae532d5de0d2a7c095e6f009dbdea4'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207801-207812.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207801-207812.nc' 'SHA256' '253289244577d0f1282d32bd7f9908530cda72752729297a29f45a29d50fdeb2'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207901-207912.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_207901-207912.nc' 'SHA256' 'd12022feddb2eaddd1b56fd30d78c493eed9cf1a8b64ea8dc3feb5345be910bb'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208001-208012.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208001-208012.nc' 'SHA256' 'af6a8937b32aed66c4123cc58f7d9834292706d69b3129fda559c29f94072f74'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208101-208112.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208101-208112.nc' 'SHA256' 'eeede6754163d65d65c9e982738c29a7e8ca9b8a519853061f3c51aaacd01577'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208201-208212.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208201-208212.nc' 'SHA256' '764bc565600d320963fb4a4d17266b068dccdabace1596591b7393099223b153'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208301-208312.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208301-208312.nc' 'SHA256' 'a764a69212098b53b5c16668c392f9480b07d0efa0318f036324887bd5edb577'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208401-208412.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208401-208412.nc' 'SHA256' 'dfbe56922516256032ad786a27f66791b6b0beda48a891d7a23002c0eb78de6f'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208501-208512.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208501-208512.nc' 'SHA256' 'db380c47d6a0bbc0897b1c2941f5d6a988f35bb15ad33ae4745f59c9d9a86045'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208601-208612.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208601-208612.nc' 'SHA256' 'c848ae70d2855482490daac2194478ba0ec586bd56e9adf400031aea2090b6e1'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208701-208712.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208701-208712.nc' 'SHA256' 'a364bdd9830d6238fd2ef94cd1ac578769848af6903a2e8d739ed2a1a97a6c01'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208801-208812.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208801-208812.nc' 'SHA256' 'b5fdf2c7301bff92ae1da5932d3ac553c8d094b630b79778cd7809bc69432ebe'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208901-208912.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_208901-208912.nc' 'SHA256' '65c09a99775392529ee2e084d3c6fc08d26433047ec76f3b0667c332d2150e87'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209001-209012.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209001-209012.nc' 'SHA256' '3e24025eec6008f4a06c512b710ee3e227446f0cf70bb02589fd13fdc964aa99'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209101-209112.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209101-209112.nc' 'SHA256' '2c0ee4edd77714e9791ad6cb237d5b36d1e48670ddf292dc2788dfc838e8a870'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209201-209212.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209201-209212.nc' 'SHA256' 'bdba52ddf94867bd48afdea1fd8d17f1dc3b438653775a8901b0522853d8d5cd'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209301-209312.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209301-209312.nc' 'SHA256' 'f59290969e0460aca26e25d341070a7ec53780a295c7cf34913401550c3eda9c'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209401-209412.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209401-209412.nc' 'SHA256' 'ed094400259d45191ca76efb8966f64612c76f66b5be4accd30295c1b6ad9bb7'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209501-209512.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209501-209512.nc' 'SHA256' 'd24ee0dc318a619b3ba99f0bde4e860d63283b5438fa9055b743819f5f35013d'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209601-209612.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209601-209612.nc' 'SHA256' '5afc52740c6c385231a64bb148cd53d2be216c28f423dd856da9ce6463f6dfd6'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209701-209712.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209701-209712.nc' 'SHA256' 'e6aa76f41a058a88850305d790c857bca9c8f070e4373ef8b75c48441c83b16c'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209801-209812.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209801-209812.nc' 'SHA256' 'f8a42c3bb8c946770726d878c0498d426fdea7a5155dad288d5f3439835355a5'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209901-209912.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_209901-209912.nc' 'SHA256' 'e267df23bbb1648df5e007f3bffc2d63922fc63ac6b47cf706783b50a299261f'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_210001-210012.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_210001-210012.nc' 'SHA256' '0aab9be84d7100daec06aed89bee4d0e6237bffae6402255d6dd9a858a5c16c5'
'clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_210101-210112.nc' 'http://esgf.nci.org.au/thredds/fileServer/replica/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp370/r12i1p1f1/Amon/clt/gr/v20200925/clt_Amon_EC-Earth3-Veg_ssp370_r12i1p1f1_gr_210101-210112.nc' 'SHA256' 'e00fed2f765eea666b6c49964a648924ab81f12bc7f4649d0430c54a6102fa42'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 87 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
